<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-14T22:45:25 IST" name="Default suite" finished-at="2025-03-14T22:45:31 IST" duration-ms="6791">
    <groups>
    </groups>
    <test started-at="2025-03-14T22:45:25 IST" name="Default test" finished-at="2025-03-14T22:45:31 IST" duration-ms="6791">
      <class name="testcases.TestLevelClass">
        <test-method is-config="true" signature="driverInstance()[pri:0, instance:testcases.TestLevelClass@222545dc]" started-at="2025-03-14T22:45:25 IST" name="driverInstance" finished-at="2025-03-14T22:45:31 IST" duration-ms="6208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInstance -->
        <test-method signature="verifyUserCanEnterEmptyName()[pri:0, instance:testcases.TestLevelClass@222545dc]" started-at="2025-03-14T22:45:31 IST" name="verifyUserCanEnterEmptyName" finished-at="2025-03-14T22:45:31 IST" duration-ms="186" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed: Entered Empty input value! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed: Entered Empty input value! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcases.TestLevelClass.verifyUserCanEnterEmptyName(TestLevelClass.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCanEnterEmptyName -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.TestLevelClass@222545dc]" started-at="2025-03-14T22:45:31 IST" name="teardown" finished-at="2025-03-14T22:45:31 IST" duration-ms="356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.TestLevelClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
